version: "3"
services:
  dashboard:
    restart: always
    build: ./Dashboard
    command: python3 -u ./main.py
    ports:
      - "80:8080"
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
